name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Trigger for parent image update
  repository_dispatch:
    types: [parent-change]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/greyltc-org/firmware-builder:20220216.0.104
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Compile
        run: |
          repo="$(pwd)"

          board="megaatmega2560"
          source_dir="main-uC"
          (cd "/${board}/src" && ln -sf "${repo}/${source_dir}"/* .)
          pio run -d "/${board}"

          board="ATmega328PB"
          source_dir="stepper-uC"
          (cd "/${board}/src" && ln -sf "${repo}/${source_dir}"/* .)
          pio run -d "/${board}"
